### ISSUE TITLE
check_ping /check_icmp dosn't work in docker container

### ISSUE THREAD

**Issue by bodsch** [monitoring-plugins/monitoring-plugins#1509]
I maintain a icinga2 docker container.
When i will use the `check_ping` command i become these result:
```
/etc/icinga2 # /usr/lib/monitoring-plugins/check_ping -4  -H 8.8.8.8 -w '100,5%' -c '200,15%'
CRITICAL - You need more args!!!
Could not open pipe:
```

as alternative, i will use `check_icmp` that doesn't work either:
```
/etc/icinga2 # /usr/lib/monitoring-plugins/check_icmp -H 8.8.8.8  -s eth0 -v
ttl set to 64
Setting alarm timeout to 10 seconds
packets: 5, targets: 1
target_interval: 0.000, pkt_interval 80.000
crit.rta: 500.000
max_completion_time: 3400.000
crit = {500000, 80%}, warn = {200000, 40%}
pkt_interval: 80000  target_interval: 0  retry_interval: 0
icmp_pkt_size: 76  timeout: 10
Illegal instruction
```
The simple `ping` works fine:
```
/etc/icinga2 # ping -4 -c 1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=45 time=15.523 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 15.523/15.523/15.523 ms
```

Now, i'm perplexed and need help.

Is this a limitation of docker, or an bug into both checks?

**Comment by sni** [comment]
`check_icmp` requires superuser permissions, so its usually owned by root with setuid root (4755). So i guess this is a limitation of docker. Or you need to start the container with more permissions.

**Comment by bodsch** [comment]
Thanks! I will tested it ASAP

**Comment by waja** [comment]
@bodsch the docker image is based on which distribution?

**Comment by bodsch** [comment]
alpine linux 3.6 (https://github.com/bodsch/docker-icinga2)
i've tested many combinations with sysctl and/or setcap and currently, i give up.
i will now work on my slides ... ;)

**Comment by bodsch** [comment]
no positive result so far :(

**Comment by guessi** [comment]
also have this issue, test with the following combination
- Ubuntu 14.04 + Nagios 4.3.4 => Pass
- Ubuntu 16.04 + Nagios 4.3.4 => Failed

and tried to add --cap-add=ALL, but doesn't help

**Comment by guessi** [comment]
Oops... issue resolved by myself,

since the Ubuntu 16.04 reduced its default packages for Docker, `ping` does not provided by default, simply execute the following command before build, `check_ping` works as expected.

`$ sudo apt install -y iputils-ping`

```
root@8cafad1c8676:/opt/nagios/libexec# cat /etc/issue.net
Ubuntu 16.04.3 LTS

root@8cafad1c8676:/opt/nagios/libexec# ./check_ping -V
check_ping v2.2.1 (nagios-plugins 2.2.1)

root@8cafad1c8676:/opt/nagios/libexec# ./check_ping -H google.com -w 1000,30% -c 1000,40%
PING OK - Packet loss = 0%, RTA = 8.56 ms|rta=8.558000ms;1000.000000;1000.000000;0.000000 pl=0%;30;40;0
```

**Comment by guessi** [comment]
@waja I can confirm that this issue will happened on alpine:3.6, and I created a PR #1509 for avoiding this issue, I'd like to invite you to review PR while you are free, thanks

@fcolista I'm here tagging you because I just found your name in [Maintainer](https://pkgs.alpinelinux.org/package/v3.6/community/x86_64/monitoring-plugins) field
in the `monitoring-plugins` package of alpine, would you mind to check the issue of `check_ping` plugins, here's the console log

```
$ docker run -it alpine:3.6
/ # apk add --no-cache monitoring-plugins
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/8) Installing libdbi (0.9.0-r0)
(2/8) Installing mariadb-common (10.1.26-r0)
(3/8) Installing mariadb-client-libs (10.1.26-r0)
(4/8) Installing db (5.3.28-r0)
(5/8) Installing libsasl (2.1.26-r10)
(6/8) Installing libldap (2.4.44-r5)
(7/8) Installing libpq (9.6.5-r0)
(8/8) Installing monitoring-plugins (2.2-r1)
OK: 14 MiB in 19 packages

/ # /usr/lib/monitoring-plugins/check_ping -V
check_ping v (monitoring-plugins 2.2)

/ # /usr/lib/monitoring-plugins/check_ping -H google.com -w 1000,30% -c 1000,40% -vvv
CMD:
CRITICAL - You need more args!!!
Could not open pipe:
```

as you can see, `CMD: ` field appears to be empty, the same symptom as I mentions in [previous comment](https://github.com/monitoring-plugins/monitoring-plugins/issues/1509#issuecomment-341444373)


it might be caused by `PING_COMMAND` detection failure [Source Code HERE](https://github.com/monitoring-plugins/monitoring-plugins/blob/master/plugins/check_ping.c#L112-L133),


I think it might have something related to `PING_COMMAND` detection during `./configure` process, and you are probably like to fix it.

FYI

**Comment by bodsch** [comment]
+1

**Comment by fcolista** [comment]
Hi guessi.
I pushed an update for monitoring-plugins on edge.
Can you please check if that upgrade fixes the issue?
Thanks.

// Francesco
\ On Mobile

**Comment by guessi** [comment]
@fcolista issue resolve after installing `monitoring-plugins (2.2-r2)` with `alpine:edge`

```
# docker run --rm -it alpine:edge
Unable to find image 'alpine:edge' locally
edge: Pulling from library/alpine
e00d546a75ad: Pull complete
Digest: sha256:23e7d843e63a3eee29b6b8cfcd10e23dd1ef28f47251a985606a31040bf8e096
Status: Downloaded newer image for alpine:edge

/ # apk add --no-cache monitoring-plugins
...
(9/9) Installing monitoring-plugins (2.2-r2)
OK: 14 MiB in 20 packages

/ # /usr/lib/monitoring-plugins/check_ping -H google.com -w 1000,30% -c 1000,40% -vvv
CMD: /bin/ping -c 5 google.com
Output: PING google.com (216.58.200.46): 56 data bytes
...
0.000000 pl=0%;30;40;0
1000.000000:30% 1000.000000:40%
```

**Comment by guessi** [comment]
@fcolista and no issue on `alpine:3.6` with `monitoring-plugins (2.2-r2)` package

```
$ docker run --rm -it alpine:3.6
/ # echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
/ # echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

/ # apk update
...

/ # apk add --update monitoring-plugins
...
(8/8) Installing monitoring-plugins (2.2-r2)
OK: 14 MiB in 19 packages

/ # /usr/lib/monitoring-plugins/check_ping -H google.com -w 1000,30% -c 1000,40% -vvv
CMD: /bin/ping -c 5 google.com
Output: PING google.com (216.58.200.238): 56 data bytes

...
PING OK - Packet loss = 0%, RTA = 1.52 ms|rta=1.518000ms;1000.000000;1000.000000;0.000000 pl=0%;30;40;0
1000.000000:30% 1000.000000:40%
```

**Comment by guessi** [comment]
@waja @fcolista
FYI, `check_ping` is now operated normally with `alpine:edge`, but `check_icmp` is still failing

```
/ # /usr/lib/monitoring-plugins/check_ping -H google.com -w 1000,30% -c 1000,40%
PING OK - Packet loss = 0%, RTA = 6.13 ms|rta=6.128000ms;1000.000000;1000.000000;0.000000 pl=0%;30;40;0

/ # /usr/lib/monitoring-plugins/check_icmp -H 8.8.8.8 -s eth0
Illegal instruction
```

however `check_ping` could be fixed #1521 
but I think it's separated plugin, separated cases

**Comment by waja** [comment]
> FYI, `check_ping` is now operated normally with `alpine:edge`, but `check_icmp` is still failing
> 
> ```
> / # /usr/lib/monitoring-plugins/check_ping -H google.com -w 1000,30% -c 1000,40%
> PING OK - Packet loss = 0%, RTA = 6.13
> ms|rta=6.128000ms;1000.000000;1000.000000;0.000000 pl=0%;30;40;0
>
> / # /usr/lib/monitoring-plugins/check_icmp -H 8.8.8.8 -s eth0
> Illegal instruction
> ```

This maybe cause by missing capabilities: https://github.com/monitoring-plugins/monitoring-plugins/issues/1509#issuecomment-328331317

**Comment by fcolista** [comment]
@waja @guessi I believe that this is due to iputils missing, it is using ping from busybox rather than GNU ping.
"apk add iputils" does resolve the issue?

**Comment by guessi** [comment]
@fcolista for the case `check_ping` for `alpine`, I would say it's dependencies description missing in package

@waja I've tested enabling all cap_add as @bodsch said [before](https://github.com/monitoring-plugins/monitoring-plugins/issues/1509#issuecomment-328331773), adding `--cap-add=ALL` doesn't help.

also, please check my comment [above](https://github.com/monitoring-plugins/monitoring-plugins/issues/1509#issuecomment-341433916), tests for Ubuntu 14.04 and Ubuntu 16.04 were run on the same host, aka. the same Docker daemon, but having the different result, so it might not related to capability?

not sure if it is Docker-specific issue or not, any idea?

**Comment by fcolista** [comment]
Sure.
This is the commit: https://git.alpinelinux.org/cgit/aports/commit/?id=a47efc325c65c9c07d2f9d685cd236cd45f79117
I'll add iputils in makedepends, according with: https://github.com/monitoring-plugins/monitoring-plugins/pull/1521/commits/77b70950e923bb075102736786fc2070b23444e6

**Comment by guessi** [comment]
@fcolista thanks

And FYI, there's duplicate `--with-ping-command` in r3 build, maybe you would like to fix it :-)

https://git.alpinelinux.org/cgit/aports/commit/?id=c42f65a3146887df9d3a70a5b0eba5e50a8cc202

**Comment by fcolista** [comment]
@guessi @waja @bodsch please check this: http://dup.pw/aports/dcc43d70
-r4 fixed the duplicate. Yes, I've noticed that @guessi .. thx!

**Comment by guessi** [comment]
@fcolista looks good to me for the r4 build

**Comment by bodsch** [comment]
i will try it also ...when i'm at home

**Comment by bodsch** [comment]
fast build of an docker container based on edge.

```
/ # cat /etc/apk/repositories
http://dl-cdn.alpinelinux.org/alpine/edge/main
http://dl-cdn.alpinelinux.org/alpine/edge/community

/ # apk search monitoring-plugins
monitoring-plugins-2.2-r4
monitoring-plugins-doc-2.2-r4
/ # apk add monitoring-plugins

/ # /usr/lib/monitoring-plugins/check_ping -H heise.de -w 1000,30% -c 1000,40%
/usr/bin/ping -6 -n -U -w 10 -c 5 heise.de
CRITICAL - Could not interpret output from ping command

/ # ping heise.de
PING heise.de (193.99.144.80) 56(84) bytes of data.
64 bytes from redirector.heise.de (193.99.144.80): icmp_seq=1 ttl=244 time=18.7 ms

/ # /usr/lib/monitoring-plugins/check_icmp -H google.com
Illegal instruction
```

**Comment by waja** [comment]
> / # /usr/lib/monitoring-plugins/check_ping -H heise.de -w 1000,30% -c 1000,40%
/usr/bin/ping -6 -n -U -w 10 -c 5 heise.de
CRITICAL - Could not interpret output from ping command
> 
> / # /usr/lib/monitoring-plugins/check_ping -H google.com -w 1000,30% -c 1000,40% -vvv
CMD: /usr/bin/ping -6 -n -U -w 10 -c 5 google.com
/usr/bin/ping -6 -n -U -w 10 -c 5 google.com
CRITICAL - Could not interpret output from ping command

And there is the problem.

**Comment by guessi** [comment]
Hi @fcolista ,

sorry for interrupt again, test again the alpine:edge but failed.

please noted the error output, it's using `/usr/bin/ping`, but not `/bin/ping`
https://git.alpinelinux.org/cgit/aports/commit/?id=dcc43d70

the correct path should be `/bin/ping`, no matter the `ping` is from busybox or iputils

```
% docker run --rm -it alpine:edge

/ # cat /etc/alpine-release
3.6.0

/ # apk add --no-cache monitoring-plugins
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/11) Installing libcap (2.25-r1)
(2/11) Installing iputils (20121221-r7)
(3/11) Installing libdbi (0.9.0-r0)
(4/11) Installing mariadb-common (10.1.28-r0)
(5/11) Installing mariadb-client-libs (10.1.28-r0)
(6/11) Installing libgcc (6.4.0-r5)
(7/11) Installing db (5.3.28-r0)
(8/11) Installing libsasl (2.1.26-r10)
(9/11) Installing libldap (2.4.45-r2)
(10/11) Installing libpq (10.0-r0)
(11/11) Installing monitoring-plugins (2.2-r4)
Executing busybox-1.27.2-r2.trigger
OK: 15 MiB in 22 packages

/ # /usr/lib/monitoring-plugins/check_ping -H google.com -w 1000,30% -c 1000,40% -vvv
CMD: /usr/bin/ping -6 -n -U -w 10 -c 5 google.com
/usr/bin/ping -6 -n -U -w 10 -c 5 google.com
CRITICAL - Could not interpret output from ping command

/ # ping
Usage: ping [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination

/ # which ping
/bin/ping
```

**Comment by fcolista** [comment]
@gissi you are perfectly right.
I'm gonna fix it today.
This should fix the @bodsch issue too.

**Comment by fcolista** [comment]
@guessi

**Comment by fcolista** [comment]
Try now with -r5. 
That should fix.

// Francesco
\\ On Mobile

**Comment by fcolista** [comment]
@guessi builder are busy right now, -r5 is not yet built...wait for 10 minutes.
We're close to release Alpine 3.7...thx!

**Comment by guessi** [comment]
@fcolista
I will check commit and version change before test, thanks for update.

**Comment by guessi** [comment]
@fcolista 
still can't get 2.2-r5, but I don't expect `ping` command will work, since `ping` command under alpine doesn't accept `-4 or -6` as argument

[2.2-r5 commit change](https://git.alpinelinux.org/cgit/aports/commit/community/monitoring-plugins/APKBUILD?id=26d8468c63c71b1ccbb1bfddd14949c16b78ecd5)

please check my [previous comment](https://github.com/monitoring-plugins/monitoring-plugins/issues/1509#issuecomment-343400262), focus on the command argument,
*but* I can only confirm the command for `PING_COMMAND`, I can only test under IPv4 environment.
`PING6_COMMAND` have *NOT* test yet.

**Comment by guessi** [comment]
@waja @sni would you consider to rewrite `check_ping` with portable shell-based version?
I think it would lower down the difficulty while porting check script into new distro

maybe I could help to rewrite into python, perl, shell, etc.

how do you think?

**Comment by fcolista** [comment]
@guessi https://git.alpinelinux.org/cgit/aports/commit/?id=0eab9fb33d792139e7ca64686fa909bdcc17700d

**Comment by guessi** [comment]
LGTM,

```
/ # apk info monitoring-plugins
monitoring-plugins-2.2-r6

/ # /usr/lib/monitoring-plugins/check_ping -4 -H google.com -w 1000,30% -c 1000,40% -vv
CMD: /bin/ping -n -U -w 10 -c 5 google.com
PING OK - Packet loss = 0%, RTA = 4.12 ms|rta=4.116000ms;1000.000000;1000.000000;0.000000 pl=0%;30;40;0
1000.000000:30% 1000.000000:40%
```

**Comment by bodsch** [comment]
I think, this Issue can be closed.
Since month, my containers works and i have no open questions!
