### ISSUE TITLE
check_disk: BTRFS show wrong free space (0% inode)

### ISSUE THREAD

**Issue by DocMAX** [monitoring-plugins/monitoring-plugins#1717]
```
docmax@zeus: ~ $ /usr/lib/monitoring-plugins/check_disk -w '3%' -c '1%' -N btrfs -u GB -P
DISK CRITICAL - free space: / 235 GB (26% inode=-); /mnt/zeus/hdd 0 GB (0% inode=-)]; /mnt/zeus/4bay_usb3 500 GB (7% inode=-); /mnt/zeus/8bay_usb3 11258 GB (21% inode=-);| /=666GB;893;911;0;921 '/ (inodes)'=0;;;0;0 /mnt/zeus/hdd=1779GB;3614;3688;0;3726 '/mnt/zeus/hdd (inodes)'=0;;;0;0 /mnt/zeus/4bay_usb3=6020GB;9035;9221;0;9315 '/mnt/zeus/4bay_usb3 (inodes)'=0;;;0;0 /mnt/zeus/8bay_usb3=40918GB;57827;59019;0;59616 '/mnt/zeus/8bay_usb3 (inodes)'=0;;;0;0
docmax@zeus: ~ $ df -h /mnt/zeus/hdd 
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda        3.7T  1.8T  2.0T  48% /mnt/zeus/hdd

```

**Comment by RincewindsHat** [comment]
Hi @DocMAX , could you provide some information (especially about `/mnt/zeus/hdd` ), e.g. if there is anything special about this file system?
It's hard to reproduce this issue without more information

**Comment by DocMAX** [comment]
Hi @RincewindsHat. Here we go:
```
docmax@zeus: ~ $ mount |grep hdd
/dev/sda on /mnt/zeus/hdd type btrfs (rw,relatime,compress=zstd:3,ssd,space_cache=v2,subvolid=5,subvol=/)
docmax@zeus: ~ $ sudo btrfs filesystem df /mnt/zeus/hdd 
Data, single: total=1.80TiB, used=1.80TiB
System, single: total=4.00MiB, used=224.00KiB
Metadata, single: total=7.01GiB, used=5.95GiB
GlobalReserve, single: total=512.00MiB, used=0.00B
docmax@zeus: ~ $ sudo btrfs device usage /mnt/zeus/hdd
/dev/sda, ID: 1
   Device size:             3.64TiB
   Device slack:              0.00B
   Data,single:             1.80TiB
   Metadata,single:         7.01GiB
   System,single:           4.00MiB
   Unallocated:             1.83TiB
```

**Comment by RincewindsHat** [comment]
Thanks, it looks like I have to read a little about how btrfs works.

Would you mind executing `check_disk` with `-vvv` (idealy the current master)

**Comment by DocMAX** [comment]
Sometimes it starts to work again. So unfortunately we have to wait till it happens again.
I did the -vvv anyway:
```
Thresholds(pct) for /proc warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev warn: 3,000000 crit 1,000000
Thresholds(pct) for /run warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/firmware/efi/efivars warn: 3,000000 crit 1,000000
Thresholds(pct) for / warn: 3,000000 crit 1,000000
calling stat on /
For /, used_pct=89 free_pct=11 used_units=797 free_units=107 total_units=921 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1073741824
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
Thresholds(pct) for /sys/kernel/security warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev/shm warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev/pts warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/fs/cgroup warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/fs/pstore warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/fs/bpf warn: 3,000000 crit 1,000000
Thresholds(pct) for /proc/sys/fs/binfmt_misc warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev/mqueue warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev/hugepages warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/kernel/debug warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/kernel/tracing warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/fs/fuse/connections warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/kernel/config warn: 3,000000 crit 1,000000
Thresholds(pct) for /proc/fs/nfsd warn: 3,000000 crit 1,000000
Thresholds(pct) for /tmp warn: 3,000000 crit 1,000000
Thresholds(pct) for /boot warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/zeus/hdd warn: 3,000000 crit 1,000000
calling stat on /mnt/zeus/hdd
For /mnt/zeus/hdd, used_pct=50 free_pct=50 used_units=1848 free_units=1876 total_units=3726 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1073741824
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
Thresholds(pct) for /var/lib/nfs/rpc_pipefs warn: 3,000000 crit 1,000000
Thresholds(pct) for /run/user/1000 warn: 3,000000 crit 1,000000
Thresholds(pct) for /run/user/1000/gvfs warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/game warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/htpc warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/x1c warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/server warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/router warn: 3,000000 crit 1,000000
Thresholds(pct) for /run/user/0 warn: 3,000000 crit 1,000000
DISK OK - free space: / 107 GB (11% inode=-); /mnt/zeus/hdd 1876 GB (50% inode=-);| /=797GB;893;911;0;921 /mnt/zeus/hdd=1848GB;3614;3688;0;3726

```

**Comment by RincewindsHat** [comment]
weird.

**Comment by DocMAX** [comment]
ok, suddenly happens again:
```
docmax@zeus: ~ $ /usr/lib/monitoring-plugins/check_disk -w '3%' -c '1%' -N btrfs -u GB -vvv
Thresholds(pct) for /proc warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev warn: 3,000000 crit 1,000000
Thresholds(pct) for /run warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/firmware/efi/efivars warn: 3,000000 crit 1,000000
Thresholds(pct) for / warn: 3,000000 crit 1,000000
calling stat on /
For /, used_pct=94 free_pct=6 used_units=850 free_units=59 total_units=921 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1073741824
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
Thresholds(pct) for /sys/kernel/security warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev/shm warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev/pts warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/fs/cgroup warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/fs/pstore warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/fs/bpf warn: 3,000000 crit 1,000000
Thresholds(pct) for /proc/sys/fs/binfmt_misc warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev/mqueue warn: 3,000000 crit 1,000000
Thresholds(pct) for /dev/hugepages warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/kernel/debug warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/kernel/tracing warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/kernel/config warn: 3,000000 crit 1,000000
Thresholds(pct) for /sys/fs/fuse/connections warn: 3,000000 crit 1,000000
Thresholds(pct) for /proc/fs/nfsd warn: 3,000000 crit 1,000000
Thresholds(pct) for /run/credentials/systemd-sysusers.service warn: 3,000000 crit 1,000000
Thresholds(pct) for /tmp warn: 3,000000 crit 1,000000
Thresholds(pct) for /boot warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/zeus/hdd warn: 3,000000 crit 1,000000
calling stat on /mnt/zeus/hdd
For /mnt/zeus/hdd, used_pct=100 free_pct=0 used_units=1885 free_units=0 total_units=3726 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1073741824
Freespace_units result=0
Freespace% result=2
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
Thresholds(pct) for /var/lib/nfs/rpc_pipefs warn: 3,000000 crit 1,000000
Thresholds(pct) for /run/user/1000 warn: 3,000000 crit 1,000000
Thresholds(pct) for /run/user/1000/gvfs warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/game warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/htpc warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/x1c warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/server warn: 3,000000 crit 1,000000
Thresholds(pct) for /mnt/router warn: 3,000000 crit 1,000000
Thresholds(pct) for /run/user/0 warn: 3,000000 crit 1,000000
DISK CRITICAL - free space: / 59 GB (6% inode=-); CRITICAL [ /mnt/zeus/hdd 0 GB (0% inode=-)];| /=850GB;893;911;0;921 /mnt/zeus/hdd=1885GB;3614;3688;0;3726

```

**Comment by DocMAX** [comment]
Not interested in fixing this anymore?

**Comment by ghciv6** [comment]
I've looked a bit in the code, but i'm not familiar with btrfs.

statvfs() may return f_bavail=0. That's the number of free blocks for unprivileged users.

If all available space is reserved for root, the output might be correct. You are using operations that can initiate this behaviour?

**Comment by ckujau** [comment]
Maybe interesting: the same happened here with `check_disk` from [nagios-plugins-disk-2.3.3-11.fc35.x86_64](https://koji.fedoraproject.org/koji/buildinfo?buildID=1793491) (Sadly, Fedora has not switched to `monitoring-plugins` yet):
```
# /usr/lib64/nagios/plugins/check_disk -w 5% -c 3% -p / -vvv
Thresholds(pct) for / warn: 5.000000 crit 3.000000
calling stat on /
For /, used_pct=100 free_pct=0 used_units=225321 free_units=0 total_units=255984 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1048576
Freespace_units result=0
Freespace% result=2
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK CRITICAL - free space: / 0 MiB (0.00% inode=-)];| /=225321MiB;243184;248304;0;255984

# df -h /
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/luks-root  250G  221G   31G  88% /

# btrfs filesystem show /
Label: none  uuid: f1093dd0-ba7e-47c7-98de-e0ac85a34972
        Total devices 1 FS bytes used 219.84GiB
        devid    1 size 249.98GiB used 220.98GiB path /dev/mapper/luks-root
```
Nothing to see here. But the concept of "free space" continues to be a [confusing topic with btrfs](https://btrfs.wiki.kernel.org/index.php/FAQ#How_much_free_space_do_I_have.3F), and indeed, from a `btrfs` perspective, the filesystem appears to be "full":

```
# btrfs filesystem df /
Data, single: total=218.97GiB, used=218.85GiB            <===
System, single: total=4.00MiB, used=48.00KiB
Metadata, single: total=2.01GiB, used=1.76GiB
GlobalReserve, single: total=373.38MiB, used=0.00B
```

But using today's checkout from `monitoring-plugins`:

```
# /usr/local/src/monitoring-plugins-git/plugins/check_disk -w 5% -c 3% -p / -vvv
Thresholds(pct) for / warn: 5.000000 crit 3.000000
calling stat on /
For /, used_pct=88 free_pct=12 used_units=225321 free_units=30775 total_units=255984 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1048576
Freespace_units result=0
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK OK - free space: / 30775MiB (12% inode=-);| /=236266192896B;254997744844;260366118420;0;268418678784
```
:tada: -- so, maybe the issue is magically fixed now?

**Comment by sni** [comment]
maybe not magically but with https://github.com/monitoring-plugins/monitoring-plugins/pull/1388
So could you try the "latest" master branch to see if it helps?

**Comment by mritzmann** [comment]
I currently have the same problem.

```shell
$ df -Th /
Filesystem     Type   Size  Used Avail Use% Mounted on
/dev/sda2      btrfs  9.8T   45G  9.8T   1% /

$ /usr/lib/nagios/plugins/check_disk -vvv --critical=200 /
calling stat on /
For /, used_pct=100 free_pct=0 used_units=45624 free_units=0 total_units=1.0239e+07 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1048576
Freespace_units result=2
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK CRITICAL - free space: CRITICAL [ / 0 MB (0% inode=-)];| /=45624MB;;10238845;0;10239045
```

```shell
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ dpkg --list | grep monitoring-plugins
ii  monitoring-plugins                   2.3.1-1                        all          Plugins for nagios compatible monitoring systems (metapackage)
ii  monitoring-plugins-basic             2.3.1-1                        amd64        Plugins for nagios compatible monitoring systems (basic)
ii  monitoring-plugins-common            2.3.1-1                        amd64        Common files for plugins for nagios compatible monitoring
ii  monitoring-plugins-standard          2.3.1-1                        amd64        Plugins for nagios compatible monitoring systems (standard)
```

> So could you try the "latest" master branch to see if it helps?

@sni Since the problem occurs on a production system without build tools, I thought I could build monitoring plugins in Docker and then copy the binary out. However, the build fails for me (tested with `master`, there is no `latest` branch).

Error: https://gist.github.com/mritzmann/1adda8c1f89b192b9c1596d1076b6c37

**Comment by mritzmann** [comment]
I tried again with 23436a18516e66469aeb4d81329d62ee4bfa7a51 (from https://github.com/monitoring-plugins/monitoring-plugins/pull/1388) instead with `master`. With this the build works, I was able to create a `check_disk` binary. And I can confirm: The problem no longer occurs.

```shell
$ /usr/lib/nagios/plugins/check_disk --critical=200 /        
DISK CRITICAL - free space: / 0 MB (0% inode=-)];| /=45818MB;;10238845;0;10239045

$ ./check_disk --critical=200 /        
DISK OK - free space: / 10193277 MB (99% inode=-);| /=45818MB;;10238845;0;10239045
```

But I'm a little confused about the version. The Debian version seems newer.

```shell
$ /usr/lib/nagios/plugins/check_disk -V                
check_disk v2.3.1 (monitoring-plugins 2.3.1)

$ ./check_disk -V
check_disk v2.1.1.127.g23436 (monitoring-plugins 2.1.2)
```

**Comment by ulfkosack** [comment]
Problem not fixed on OpenSuSE appliance. Can't find any reason, why check gone critical at this time (2022-06-24 12:24:58).

exchange:~ # zypper se -si monitoring-plugins-disk
Loading repository data...
Warning: Repository 'debug-update' appears to be outdated. Consider using a different mirror or server.
Warning: Repository 'repo-backports-debug-update' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...

S  | Name                    | Type    | Version     | Arch   | Repository
---+-------------------------+---------+-------------+--------+----------------
i+ | monitoring-plugins-disk | package | 2.3.1-3.9.2 | x86_64 | repo-sle-update

```
exchange:~ # df -Th /
Filesystem     Type   Size  Used Avail Use% Mounted on
/dev/sda3      btrfs  200G  111G   90G  56% /
```

```
exchange:~ # /usr/lib/nagios/plugins/check_disk -vvv --critical=200 /
calling stat on /
For /, used_pct=100 free_pct=0 used_units=112764 free_units=0 total_units=204776 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1048576
Freespace_units result=2
Freespace% result=0
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK CRITICAL - free space: CRITICAL [ / 0 MB (0% inode=-)];| /=112764MB;;204576;0;204776
```

```
exchange:~ # cat /etc/os-release
NAME="grommunio"
VERSION="2022.05.1"
ID="grommunio-lds"
ID_LIKE="suse"
VERSION_ID="2022.05.1"
PRETTY_NAME="grommunio"
ANSI_COLOR="0;36"
HOME_URL="https://grommunio.com/"
DOCUMENTATION_URL="https://docs.grommunio.com/"
```

Which additional informations do you need?

**Comment by RincewindsHat** [comment]
@ulfkosack Your problem is like related to the failure of the current `check_disk` to get the real inode numbers from a btrfs.
Trying this on my machine led me to a slightly confusing behaviour of `statvfs` where given the mount point the block numbers seem to be correct and give the block device path the inode numbers are correct.
No idea why, but it explains your particular case, where, as you can see, the inode numbers are obviously nonsense.
Could you test https://github.com/RincewindsHat/monitoring-plugins/tree/check_disk_cleanup for me in the mean time. It has a workaround which is ugly as hell, but might suffice.

**Comment by Seb35** [comment]
I observed this issue on Debian 11 (version 2.3.1-1) but it is solved with Debian 11 backports (version 2.3.3-5~bpo11+1). I also tried the master version ([7cf099c](https://github.com/monitoring-plugins/monitoring-plugins/commit/7cf099cfb4a0e2f99943ae44bf42c23424bdc19d)) and it works fine also.

In the comment of @ulfkosack, the [result of the master version](https://github.com/monitoring-plugins/monitoring-plugins/issues/1717#issuecomment-1167648189) seems fine: there are 45 GiB free (not 0 MiB as the comment before) and the parameter `--critical=200` instructs to say critical if it is less than 200 GiB.

**Comment by waja** [comment]
@Seb35 So what you wonna say is, that it is fixed at least with 2.3.3-5. Is this correct?

**Comment by RincewindsHat** [comment]
So I did some research on *btrfs* regarding this and atm I am mostly convinced that `check_disk` is wrong here and does not know enough about *btrfs* to produce a reliable statement.

Free/Used space is not limited to a single subvolume in *btrfs* and the number of Inodes is dynamic (with an upper border of 2^64).

I think `check_disk` should not be used for btrfs filesystems (and the same is probably true for *zfs*)

**Comment by Seb35** [comment]
> @Seb35 So what you wonna say is, that it is fixed at least with 2.3.3-5. Is this correct?

If it would be up to me, yes.

In btrfs the computation of the free space is complex, because there is no definitive number, it is up to the allocator to use space when actual data are written (there are group blocks of type data or metadata, as well as balancing between different devices for raid1/5/6 profiles (e.g. this [issue for raid1c3 profiles](https://github.com/kdave/btrfs-progs/issues/277))), so there no deterministic number fixed in advance.

The kernel gives two numbers in [btrfs_statfs](https://github.com/torvalds/linux/blob/23f108dc9ed26100b1489f6a9e99088d4064f56b/fs/btrfs/super.c#L2032):
* bfree: total size minus occupied space (either data or metadata), so this number is an exact number but is not really useful because free space in metadata blocks is not really useful for the user,
* bavail: estimation of free space in current data blocks + free space in unallocated space (where blocks are distributed according to the raid1/5/6 profile), so this number is the most useful number for the users but only an estimation.

In my system where there the problem occurs, I have bfree = 168590 MiB and bavail = 168777 MiB, so the difference is only 186 MiB (≈0,11%). So the estimation of bavail is obviously slightly wrong, but `check_disk` should not say the available disk is `0` (so #1388 is fine for btrfs if there are no side-effects for other filesystems).

**Comment by Seb35** [comment]
About the inodes, there is no tracking of number of used inodes in btrfs, the numbers `f_files` and `f_ffree` returned by `statfs` or `statvfs` are always `0`. See also [this blog post](https://mpdesouza.com/blog/btrfs-for-mere-mortals-inode-allocation/) with references.

I saw your [commit here](https://github.com/monitoring-plugins/monitoring-plugins/commit/ae4859850c32a1603bf8027539a6023895aeb5fc), but according to manpages of [`statfs`](https://man7.org/linux/man-pages/man2/statfs.2.html) or [`statvfs`](https://man7.org/linux/man-pages/man2/statvfs.2.html), the path is _any_ file in the filesystem to be checked, so when it is `"/dev/sda1\0"` (e.g.) then the filesystem is the tmpfs mounted on /dev.

It can be checked with the following program:
```c
#include <sys/vfs.h>
#include <sys/stat.h>
#include <stdio.h>

int main( int argc, char** argv ) {

	struct statfs buf;
	char file[10] = "/dev/sda1\0";

	statfs( file, &buf );

	printf( "f_type=0x%08x\n", buf.f_type );
	printf( "f_blocks=%d\n", buf.f_blocks );
	printf( "f_bsize=%d\n", buf.f_bsize );
	printf( "f_bfree=%d\n", buf.f_bfree );
	printf( "f_bavail=%d\n", buf.f_bavail );
	printf( "f_files=%d\n", buf.f_files );
	printf( "f_ffree=%d\n", buf.f_ffree );

	return 0;
}
```

The result is:
```text
f_type=0x01021994
f_blocks=982817
f_bsize=4096
f_bfree=982817
f_bavail=982817
f_files=982817
f_ffree=982290
```
and the type 0x01021994 is the [type documented as TMPFS_MAGIC](https://man7.org/linux/man-pages/man2/statfs.2.html).
